---
# vars file for common

wildfly_dir: 'wildfly-9.0.0.Final'
path: "/home/admin/"
oracle: "/home/admin/wildfly-9.0.0.Final/modules/system/layers/base/com/oracle/main/"
standalone: "/home/admin/wildfly-9.0.0.Final/standalone/configuration/"
