---
# tasks file for common

- name: add slave user
  command: ./bin/add-user.sh -e -cw -u slave password chdir=/opt/{{ wildfly_dir }}

- name: Copy wildfly config file
  copy:
    src: master_conf.j2
    dest: /etc/default/wildfly.conf

- name: Copy wildfly script 
  copy:
    src: wildfly-init-redhat.sh
    dest: /etc/init.d
    mode: '0700'

- name: enable wildfly server script
  shell: chkconfig --add wildfly-init-redhat.sh

- name: enable wildfly server on startup
  shell: chkconfig wildfly-init-redhat.sh on

- name: restart wildfly in all cases 
  service:
    name: wildfly-init-redhat
    state: restarted
