---
# tasks file for common

- name: add slave user
  command: ./bin/add-user.sh -e -cw -u slave password chdir=/opt/{{ jboss_dir }}

- name: start jboss server
  shell: su jboss -c "nohup ./bin/domain.sh --host-config=host-master.xml
         -bmanagement=host-master -b=master > /dev/null 2>&1 &" chdir=/opt/{{ jboss_dir }}

