---
# tasks file for common
- block:
  - name: add slave user
    command: ./bin/add-user.sh -e -cw -u slave password chdir=/opt/{{ wildfly_dir }}

  - name: Copy wildfly config file
    copy:
      src: master_conf.j2
      dest: /etc/default/wildfly.conf

  - name: Copy wildfly script 
    copy:
      src: "{{ wildfly_script }}"
      dest: /etc/init.d
      mode: '0700'
  tags: [config_master]

- block:
  - name: enable wildfly server script
    shell: chkconfig --add "{{ wildfly_script }}"

  - name: enable wildfly server on startup
    shell: chkconfig "{{ wildfly_script }}" on

  - name: restart wildfly in all cases 
    service:
      name: wildfly-init-redhat
      state: restarted
  tags: [start_master]
